<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AuthService.proto

namespace GPBMetadata;

class AuthService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
°
AuthService.protoAuthService"
AuthRequest
token (	"D
User

id (	
name (	
email (	
verified_at (	"Q
AuthResponse
success (
message (	
user (2.AuthService.User2O
AuthService@
	AuthCheck.AuthService.AuthRequest.AuthService.AuthResponsebproto3'
        , true);

        static::$is_initialized = true;
    }
}

